packages:
    - apps/*
    - packages/*

blockExoticSubdeps: true

catalog:
    "@expo/vector-icons": ^15.1.1
    "@nanostores/react": ^1.1.0
    "@notifee/react-native": ^9.1.8
    "@types/node": ^24.10.1
    "@vex-chat/crypto": 7.0.0
    "@vex-chat/libvex": 7.0.0
    "@vex-chat/spire": 2.0.0
    "@vex-chat/types": 4.0.0
    dompurify: ^3.4.0
    expo-background-fetch: ~55.0.15
    expo-background-task: ~55.0.17
    expo-audio: ~55.0.14
    expo-clipboard: ~55.0.13
    expo-constants: ~55.0.13
    expo-crypto: ~55.0.14
    expo-document-picker: ~55.0.13
    expo-file-system: ~55.0.17
    expo-image-manipulator: ^55.0.15
    expo-intent-launcher: ~55.0.12
    expo-sharing: ~55.0.18
    expo-task-manager: ~55.0.15
    expo-video: ~55.0.17
    highlight.js: ^11.11.1
    kysely: ^0.28.17
    marked: ^15.0.12
    msgpackr: ^1.11.5
    nanostores: ^1.2.0
    react: 19.2.0
    react-dom: 19.2.0
    react-native-passkey: 3.3.3
    svelte: ^5.55.7
    typescript: ~5.9.3
    uuid: ^14.0.0
    vitest: 3.2.4
    zod: ^4.1.12

catalogMode: strict

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
    - "@vex-chat/libvex"
    - "@vex-chat/types"
    - "@vex-chat/crypto"
    - "@vex-chat/spire"
    - expo-background-fetch
    - expo-background-task
    - expo-task-manager
    - unimodules-app-loader
    - uuid
    - dompurify
    - qs
    - svelte
    - devalue
    - fast-xml-builder
    - kysely
    - ws
